#!/bin/bash

echo $0 - a PBS datastore to USB media sync tool

# change to script dir
cd "$(dirname "$0")"

# collect backup media data
./gather_backup_media.sh

function cleanup_and_exit () {
	umount $backup_target
};


# default settings
backup_source=/PBS-WD-2TB-intern
backup_fs_label=nbp-usb-backup
backup_target=/media/$backup_fs_label
backup_pbs_datastore_folder=pbs-datastore-backup

# mount backup media
umount $backup_target
mkdir $backup_target
mount /dev/disk/by-label/$backup_fs_label $backup_target
mkdir $backup_target/$backup_pbs_datastore_folder

# check for backup media marker file
echo -n "Checking for marker file $backup_target/.pbs-usb-backup-media . . ."
if [ -f "${backup_target}/.pbs-usb-backup-media" ]
then
	echo " . . found"
	# rsync over datastore to usb backup media
	echo "rsync data from $backup_source to $backup_target/$backup_pbs_datastore_folder"
	rsync -a --stats --exclude='lost+found' --delete $backup_source $backup_target/$backup_pbs_datastore_folder
	if [ $? = 0 ]
	then
		echo "rsync ok"
	else
		echo "rsync reported ERRORS!"
	fi
else
	echo " . . not found. Exiting."
	cleanup_and_exit 
	exit 1
fi
cleanup_and_exit 
