#!/bin/bash
timestamp=$(date +"%Y.%m.%d %H:%M:%S")
echo $timestamp : ${1} >>/tmp/vzdump-testhook-out.txt

case "${1}" in
	job-end)
		echo "+++++ Backup START" $(date +"%Y.%m.%d %H:%M:%S") >>/var/log/pbs-rdx-backup.log
		/opt/proxmox-rdx-backup/pbs-rdx-backup >>/var/log/pbs-rdx-backup.log 2>&1
		echo "----- Backup END  " $(date +"%Y.%m.%d %H:%M:%S") >>/var/log/pbs-rdx-backup.log
		;;
esac

