#!/bin/bash
timestamp=$(date +"%Y.%m.%d %H:%M:%S")

case "${1}" in
	job-start)
		echo "+++++ Backup START" $(date +"%Y.%m.%d %H:%M:%S") >>/var/log/pbs-zfs-backup.log
		;;
	job-end)
		/opt/pbs-rdx-backup/pbs-zfs-backup >>/var/log/pbs-zfs-backup.log 2>&1
		echo "----- Backup END  " $(date +"%Y.%m.%d %H:%M:%S") >>/var/log/pbs-zfs-backup.log
		;;
esac

